/**
 * com.foo is a group of bar utils for operating on foo things.
 */
package pl.maciejwojs.ar00k.bestnotepadevercreaated.db

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.time.format.DateTimeFormatter

/**
 * @brief Represents a Note entity with title, content, timestamps, and an ID.
 *
 * The Note class is annotated with @Entity to indicate that it is a database entity.
 * It includes a title, content, modification timestamp, creation timestamp, and a unique ID.
 *
 * @property title The title of the note.
 * @property content The content of the note.
 * @property modificationTime The last modification timestamp of the note, formatted as "dd-MM-yyyy".
 * @property creationTime The creation timestamp of the note, formatted as "dd-MM-yyyy".
 * @property noteID The unique identifier for each note, auto-generated by the database.
 */
@Entity(tableName = "notes")
data class Note(
    val title: String,
    val content: String,
    val modificationTime: String = LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")).toString(),
    val creationTime: String = LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")).toString(),
    @PrimaryKey(autoGenerate = true)
    val noteID: Int = 0
)
