name: Compile app
on:
  push:
    tags:
      - '*.*.*'

env:
  JAVA_VERSION: 21

jobs:
  Comipile_APP:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
          cache: 'gradle'
            
      - name: gradlew
        run: |
          chmod 777 ./gradlew 
          ./gradlew build

      - name: release the apk
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./app/build/outputs/apk/debug/app-debug.apk"

      - name: Webhook DC notification
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          download_link=$(curl -s https://api.github.com/repos/MaciejWojs/notepad-app/releases/latest | jq -r '.assets[] | select(.name == "app-debug.apk") | .browser_download_url')
          curl -s -H "Content-Type: application/json" -d "{\"content\": \"Link do pobrania najnowszej aktualizacji: ${download_link} @everyone\"}" ${{ secrets.DISCORD_WEBHOOK_URL }} &> /dev/null