name: Create documentation
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  Create_documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: install packages
        run: sudo apt update && sudo apt install -y graphviz
      - name: Preatify doxygen
        run: |
          latest_version=$(curl -s https://api.github.com/repos/jothepro/doxygen-awesome-css/releases/latest | jq -r '.tag_name')
          download_url="https://github.com/jothepro/doxygen-awesome-css/archive/refs/tags/${latest_version}.tar.gz"
          wget -O doxygen-awesome-css.tar.gz "$download_url"

          tar -xzf doxygen-awesome-css.tar.gz
          rm -rf doxygen-awesome-css.tar.gz
          ls -la
          mv doxygen-awesome-css*/ doxygen-awesome-css/
          cp doxygen-awesome-css/doxygen-awesome.css . 
          cp doxygen-awesome-css/doxygen-awesome-sidebar-only.css .
          echo <<END
          GENERATE_TREEVIEW      = YES            
          DISABLE_INDEX          = NO
          FULL_SIDEBAR           = NO
          HTML_EXTRA_STYLESHEET  = doxygen-awesome.css doxygen-awesome-sidebar-only.css
          END >> Doxyfile
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@edge
        with:
          enable-latex: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
      - name: Rename PDF file
        run: |
          cp ./docs/latex/refman.pdf ./main.pdf
          sudo chmod 777 ./docs/latex/refman.pdf 
      - name: release the pdf
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "main.pdf"
